version: "3.7"

services:
    # image project
    app:
        container_name: dept-code
        build:
            context: .
            dockerfile: Dockerfile
        image: dept/assessment-app
        restart: always
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel-9

    # nginx
    nginx:
        container_name: dept-nginx
        image: nginx:alpine
        restart: always
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-9

    # db mysql
    mysql:
        container_name: dept-mysql
        image: mysql:5.7.22
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel-9

    # redis
    redis:
        container_name: dept-redis
        image: redis:latest
        networks:
            - laravel-9

networks:
    laravel-9:
        driver: bridge
